# Generated by Django 5.2.6 on 2025-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=300)),
                ("page_range", models.CharField(blank=True, max_length=1, null=True)),
                ("pages", models.CharField(max_length=6)),
                ("color", models.CharField(max_length=4)),
                ("orientation", models.CharField(max_length=1)),
                ("file_type", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "files",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_title", models.CharField(max_length=32)),
                ("default_color", models.CharField(max_length=4)),
                ("default_orientation", models.CharField(max_length=1)),
                ("printer_profile", models.TextField()),
            ],
        ),
    ]
