# Generated by Django 5.2.6 on 2025-09-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
    ]
